### ISSUE TITLE
Feature Request @ngrx/entity

### ISSUE THREAD

**Issue by lexcaraig** [kmathy/ngx-reduxor#1]
It would be great if this will have an auto generated `@ngrx/entity` the new package of ngrx. :)

**Comment by kmathy** [comment]
Really interesting! I will implement it soon when I will have some free time, probably during the last week of this month 
Thanks 👍

**Comment by lexcaraig** [comment]
Yeah, sure! Let me know of any updates. Thanks a lot! :)

**Comment by kmathy** [comment]
Hi!

This feature is quite difficult to implement, I mean for the best structure possible. 
Without HTTP request, it is easy to manage the state. However, using HTTP, I wanted to avoid the previous structure:
```
case CREATE_FOO: ...
case CREATE_FOO_SUCCESS: ...
case CREATE_FOO_ERROR: ...
```
Because there are many methods provided by @ngrx/entities. It can be interesting to wait the server validation before calling the right method.
For the error, I think I have something: only a ERROR action for each object and we pass the previous state called, for example:
```
CREATE_FOO: ...
...
ERROR: ... // action.type === 'CREATE_FOO'
```
So that, we can keep a track for a certain error

Thus, what is the best strategy we can implement?

**Comment by lexcaraig** [comment]
Hi

I have created a dicussion page in the wiki. We can put it in there and let’s see what we can do for this implementation. :)

I’ll try to make an good example and post it there so you can see. If you want, I'll be the one to implement the `ngrx/entity` on this project. Just let me know. Thanks!
