### ISSUE TITLE
Yeoman Generator request

### ISSUE THREAD

**Issue by jhcao23** [kmathy/ngx-reduxor#13]
This is a wonderful generator and I love it!
However, I, as a Java and Typescript developer who has no feelings on pure Javascript, really am not an expert on plopjs and plopjs doesn't support typescript at all and it won't. And there is no better straight tutorial on the web for now.
So is there any possibility to create a new generator like Yeoman which might support Typescript and easier to learn?
Thanks so much!

**Comment by kmathy** [comment]
Hi @jhcao23 ,

I appreciate the kind words, thank you! 

I know it's quite difficult to understand how plopjs works, and I understand your problem (I came from a Java world too!)

However, I've completely stopped working on this open source project for a long time, because I have no time and there are better ways to define your Redux architecture. **ngrx** created schematics and it is supported by Angular-CLI. Moreover, if you want to use a more Angular-way to use Redux in your app, there is **NGXS**. 

But if these solutions are not suited your requirements, just fork this project and continue the development. I can say you that I've worked on it with a scalable architecture, you 'll find quite easily what you need. To handle the template, plopjs uses [Handlebars](https://handlebarsjs.com/) and [Inquirer](https://github.com/SBoudrias/Inquirer.js/) for the command line. Don't be afraid to dive in it, you can make great things ;)

I hope you'll find your happiness and I wish you success for your project!

**Comment by jhcao23** [comment]
so sweet words! Thank you so much @kmathy !
